spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${JDBC_DATABASE_URL}
  properties:
    hibernate:
      jdbc:
        lob:
          non_contextual_creation: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
            scope:
              - email
server:
  servlet:
    session:
      timeout: 60m