spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${JDBC_DATABASE_URL}
  properties:
    hibernate:
      jdbc:
        lob:
          non_contextual_creation: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}