spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: com.h2.jdbc.Driver
    initialize: true
  properties:
    hibernate:
      jdbc:
        lob:
          non_contextual_creation: true
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration