/**
 * Regenerates app/helpers/bible-book-word-counts.ts from the Berean Standard
 * Bible (public domain / CC0 since 2023-04-30), via the scrollmapper
 * bible_databases JSON export. Word counts drive the reading-time estimates on
 * the public Books of the Bible pages and the reading-time guide.
 *
 * Usage: npx tsx ./scripts/generate-bible-word-counts.ts
 * Also prints a markdown table (book, chapters, verses, words, minutes at
 * 238 wpm) for pasting into the "how long does it take" guide.
 */
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
// @mybiblelog/shared is CJS; see scripts/i18n/verify-i18n-keys.ts
import shared from '@mybiblelog/shared';

const { Bible } = shared;

const SOURCE_URL = 'https://raw.githubusercontent.com/scrollmapper/bible_databases/2025/formats/json/BSB.json';
const WORDS_PER_MINUTE = 238;

type BsbJson = {
  books: { name: string; chapters: { verses: { text: string }[] }[] }[];
};

const countWords = (text: string): number => (text.match(/[A-Za-z0-9’']+/g) ?? []).length;

const main = async () => {
  const res = await fetch(SOURCE_URL);
  if (!res.ok) {
    throw new Error(`Failed to download ${SOURCE_URL}: ${res.status}`);
  }
  const bsb = await res.json() as BsbJson;
  if (bsb.books.length !== Bible.getBookCount()) {
    throw new Error(`Expected ${Bible.getBookCount()} books, got ${bsb.books.length}`);
  }

  // The export lists books in canonical order, so position n is bibleOrder n + 1.
  const wordCounts = bsb.books.map(book =>
    book.chapters.reduce((sum, chapter) =>
      sum + chapter.verses.reduce((verseSum, verse) => verseSum + countWords(verse.text), 0), 0));

  const outFile = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../app/helpers/bible-book-word-counts.ts');
  const lines = wordCounts.map((count, i) => `  ${count}, // ${Bible.getBookName(i + 1)}`);
  await fs.writeFile(outFile, `// Generated by scripts/generate-bible-word-counts.ts — do not edit by hand.
// Word counts per book (index 0 = Genesis) from the Berean Standard Bible
// (public domain / CC0 since 2023-04-30): ${SOURCE_URL}
const bibleBookWordCounts: readonly number[] = [
${lines.join('\n')}
];

export default bibleBookWordCounts;
`);

  console.log('| Book | Chapters | Verses | Words | Reading time |');
  console.log('|---|---:|---:|---:|---:|');
  wordCounts.forEach((count, i) => {
    const book = i + 1;
    const minutes = Math.max(1, Math.round(count / WORDS_PER_MINUTE));
    console.log(`| ${Bible.getBookName(book)} | ${Bible.getBookChapterCount(book)} | ${Bible.getBookVerseCount(book).toLocaleString('en-US')} | ${count.toLocaleString('en-US')} | ${minutes} min |`);
  });
  const total = wordCounts.reduce((a, b) => a + b, 0);
  const ot = wordCounts.slice(0, 39).reduce((a, b) => a + b, 0);
  console.log(`\nTotal ${total} (OT ${ot}, NT ${total - ot}); ${(total / WORDS_PER_MINUTE / 60).toFixed(1)} h`);
};

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
