// Generated by scripts/generate-bible-word-counts.ts — do not edit by hand.
// Word counts per book (index 0 = Genesis) from the Berean Standard Bible
// (public domain / CC0 since 2023-04-30): https://raw.githubusercontent.com/scrollmapper/bible_databases/2025/formats/json/BSB.json
const bibleBookWordCounts: readonly number[] = [
  35121, // Genesis
  29113, // Exodus
  22106, // Leviticus
  28767, // Numbers
  25820, // Deuteronomy
  16448, // Joshua
  16837, // Judges
  2421, // Ruth
  22652, // 1 Samuel
  18771, // 2 Samuel
  22446, // 1 Kings
  21883, // 2 Kings
  18657, // 1 Chronicles
  24060, // 2 Chronicles
  6524, // Ezra
  9552, // Nehemiah
  5115, // Esther
  16671, // Job
  39491, // Psalms
  14144, // Proverbs
  5175, // Ecclesiastes
  2539, // Song of Songs
  34084, // Isaiah
  39827, // Jeremiah
  3216, // Lamentations
  36203, // Ezekiel
  10641, // Daniel
  4917, // Hosea
  1855, // Joel
  3882, // Amos
  615, // Obadiah
  1231, // Jonah
  2898, // Micah
  1144, // Nahum
  1351, // Habakkuk
  1500, // Zephaniah
  1056, // Haggai
  5800, // Zechariah
  1724, // Malachi
  22348, // Matthew
  13877, // Mark
  24044, // Luke
  18462, // John
  22548, // Acts
  9410, // Romans
  9259, // 1 Corinthians
  6013, // 2 Corinthians
  3090, // Galatians
  3005, // Ephesians
  2162, // Philippians
  1973, // Colossians
  1856, // 1 Thessalonians
  1047, // 2 Thessalonians
  2334, // 1 Timothy
  1647, // 2 Timothy
  926, // Titus
  452, // Philemon
  6779, // Hebrews
  2248, // James
  2376, // 1 Peter
  1535, // 2 Peter
  2505, // 1 John
  296, // 2 John
  309, // 3 John
  606, // Jude
  11332, // Revelation
];

export default bibleBookWordCounts;
